<?php
declare(strict_types=1);

// PricingDay SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

PricingDayUtility::setRegistrar(function (PricingDayUtility $u): void {
    $u->clean = [PricingDayClean::class, 'call'];
    $u->done = [PricingDayDone::class, 'call'];
    $u->make_error = [PricingDayMakeError::class, 'call'];
    $u->feature_add = [PricingDayFeatureAdd::class, 'call'];
    $u->feature_hook = [PricingDayFeatureHook::class, 'call'];
    $u->feature_init = [PricingDayFeatureInit::class, 'call'];
    $u->fetcher = [PricingDayFetcher::class, 'call'];
    $u->make_fetch_def = [PricingDayMakeFetchDef::class, 'call'];
    $u->make_context = [PricingDayMakeContext::class, 'call'];
    $u->make_options = [PricingDayMakeOptions::class, 'call'];
    $u->make_request = [PricingDayMakeRequest::class, 'call'];
    $u->make_response = [PricingDayMakeResponse::class, 'call'];
    $u->make_result = [PricingDayMakeResult::class, 'call'];
    $u->make_point = [PricingDayMakePoint::class, 'call'];
    $u->make_spec = [PricingDayMakeSpec::class, 'call'];
    $u->make_url = [PricingDayMakeUrl::class, 'call'];
    $u->param = [PricingDayParam::class, 'call'];
    $u->prepare_auth = [PricingDayPrepareAuth::class, 'call'];
    $u->prepare_body = [PricingDayPrepareBody::class, 'call'];
    $u->prepare_headers = [PricingDayPrepareHeaders::class, 'call'];
    $u->prepare_method = [PricingDayPrepareMethod::class, 'call'];
    $u->prepare_params = [PricingDayPrepareParams::class, 'call'];
    $u->prepare_path = [PricingDayPreparePath::class, 'call'];
    $u->prepare_query = [PricingDayPrepareQuery::class, 'call'];
    $u->graphql_body = [PricingDayGraphql::class, 'body'];
    $u->graphql_errors = [PricingDayGraphql::class, 'errors'];
    $u->result_basic = [PricingDayResultBasic::class, 'call'];
    $u->result_body = [PricingDayResultBody::class, 'call'];
    $u->result_headers = [PricingDayResultHeaders::class, 'call'];
    $u->transform_request = [PricingDayTransformRequest::class, 'call'];
    $u->transform_response = [PricingDayTransformResponse::class, 'call'];
});
